src/Entity/Service.php
<?php

namespace App\Entity;

use App\Repository\ServiceRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ServiceRepository::class)]
class Service
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Title = null;

    #[ORM\Column(length: 255)]
    private ?string $Description = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\HoraireRepository;
use App\Repository\ServiceRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    #[Route('/', name: 'app_home')]
    public function index(ServiceRepository $repo, HoraireRepository $horaire): Response
    {
        return $this->render('home/index.html.twig', [
            'controller_name' => 'HomeController',
            'service'=>$repo->findAll(),
            'horairedujour'=>$horaire->findAll(),
        ]);
    }
}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'accueil - V.Parrot!{% endblock %}
{% block stylesheets %}
            <link href="{{ asset('css/Home.css') }}" rel="stylesheet" />
        {% endblock %}
{% block body %}

{% include 'navbar.html.twig' %}

     <div class="herobanner">
          <h1>  la qualité automobile à votre service !</h1>
</div>
     <content>
   <h1 class="Heading1"> nos services de réparation automobiles</h1>
    <div class="mainContent">
     {% include 'home/serviceCard.html.twig' %}
     </div>
     </content>

{% endblock %}

templates/home/serviceCard.html.twig
  
  {% block stylesheets %}
            <link href="{{ asset('css/serviceCard.css') }}" rel="stylesheet" />
        {% endblock %}
  

   
        {% for service in service %}
    
            <div class="cardContainer">
         
                <h1>{{service.title}}</h1>
                <div class="descriptionBox">
                <div class="detail"><p>Détail:</p></div>
                <p>{{service.description}}</p>
            
            <div class="btn">
                <button >Envoyer une demande</button>
            </div>
            </div>
            </div>
             
        {% endfor %}